blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ å‚ä¸è®¨è®º
    url: https://github.com/datawhalechina/learn-python-the-smart-way-v2/discussions
    about: issues æš‚æ—¶åªæ¥æ”¶æ•™ç¨‹å†…å®¹é—®é¢˜åé¦ˆï¼ˆå†…å®¹é”™è¯¯ã€æ”¹è¿›ææ¡ˆç­‰ï¼‰ï¼Œåœ¨æ•™ç¨‹å­¦ä¹ è¿‡ç¨‹ä¸­é‡åˆ°çš„å…¶ä»–ä»»ä½•é—®é¢˜ï¼Œæ¬¢è¿ç§»æ­¥åˆ° Datawhale èªæ˜åŠæ³•å­¦ Python ç¤¾åŒºçš„è®¨è®ºã€‚
